=begin
#FrankenSpec

#Bandwidth's Frankensteined API Spec

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.2.1

=end

require 'spec_helper'
require 'json'

# Unit tests for RubySdk::CallsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CallsApi' do
  before do
    # run before each test
    @api_instance = RubySdk::CallsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CallsApi' do
    it 'should create an instance of CallsApi' do
      expect(@api_instance).to be_instance_of(RubySdk::CallsApi)
    end
  end

  # unit tests for create_call
  # Create Call
  # Creates an outbound phone call.
  # @param account_id 
  # @param create_call_request 
  # @param [Hash] opts the optional parameters
  # @return [CreateCallResponse]
  describe 'create_call test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_call
  # Get Call Information
  # Returns near-realtime metadata about the specified call.
  # @param account_id 
  # @param call_id 
  # @param [Hash] opts the optional parameters
  # @return [CallState]
  describe 'get_call test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for modify_call
  # Update Call
  # Interrupts and replaces an active call&#39;s BXML document.
  # @param account_id 
  # @param call_id 
  # @param modify_call_request 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'modify_call test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
