=begin
#FrankenSpec

#Bandwidth's Frankensteined API Spec

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.2.1

=end

require 'spec_helper'
require 'json'

# Unit tests for RubySdk::ParticipantsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ParticipantsApi' do
  before do
    # run before each test
    @api_instance = RubySdk::ParticipantsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ParticipantsApi' do
    it 'should create an instance of ParticipantsApi' do
      expect(@api_instance).to be_instance_of(RubySdk::ParticipantsApi)
    end
  end

  # unit tests for create_participant
  # Create Participant
  # Create a new participant under this account.  Participants are idempotent, so relevant parameters must be set in this function if desired. 
  # @param account_id Account ID
  # @param [Hash] opts the optional parameters
  # @option opts [Participant] :participant Participant parameters
  # @return [InlineResponse200]
  describe 'create_participant test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_participant
  # Delete Participant
  # Delete participant by ID.
  # @param account_id Account ID
  # @param participant_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_participant test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_participant
  # Get Participant
  # Get participant by ID.
  # @param account_id Account ID
  # @param participant_id Participant ID
  # @param [Hash] opts the optional parameters
  # @return [Participant]
  describe 'get_participant test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
