=begin
#FrankenSpec

#Bandwidth's Frankensteined API Spec

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.2.1

=end

require 'spec_helper'
require 'json'

# Unit tests for RubySdk::PhoneNumberLookupApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PhoneNumberLookupApi' do
  before do
    # run before each test
    @api_instance = RubySdk::PhoneNumberLookupApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PhoneNumberLookupApi' do
    it 'should create an instance of PhoneNumberLookupApi' do
      expect(@api_instance).to be_instance_of(RubySdk::PhoneNumberLookupApi)
    end
  end

  # unit tests for lookup_request
  # Create Request
  # Create a TN Lookup Order.
  # @param account_id The ID of the Bandwidth account that the user belongs to.
  # @param order_request 
  # @param [Hash] opts the optional parameters
  # @return [OrderResponse]
  describe 'lookup_request test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for lookup_request_status
  # Query Request Status
  # Query an existing TN Lookup Order.
  # @param account_id The ID of the Bandwidth account that the user belongs to.
  # @param request_id 
  # @param [Hash] opts the optional parameters
  # @return [OrderStatus]
  describe 'lookup_request_status test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
