=begin
#FrankenSpec

#Bandwidth's Frankensteined API Spec

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.2.1

=end

# Common files
require_relative 'openapi_ruby_sdk/api_client'
require_relative 'openapi_ruby_sdk/api_error'
require_relative 'openapi_ruby_sdk/version'
require_relative 'openapi_ruby_sdk/configuration'

# Models
require_relative 'openapi_ruby_sdk/models/api_error'
require_relative 'openapi_ruby_sdk/models/bandwidth_callback_message'
require_relative 'openapi_ruby_sdk/models/bandwidth_message'
require_relative 'openapi_ruby_sdk/models/bandwidth_message_item'
require_relative 'openapi_ruby_sdk/models/bandwidth_messages_list'
require_relative 'openapi_ruby_sdk/models/call_callback'
require_relative 'openapi_ruby_sdk/models/call_recording_metadata'
require_relative 'openapi_ruby_sdk/models/call_state'
require_relative 'openapi_ruby_sdk/models/conference_callback'
require_relative 'openapi_ruby_sdk/models/conference_member_state'
require_relative 'openapi_ruby_sdk/models/conference_recording_metadata'
require_relative 'openapi_ruby_sdk/models/conference_state'
require_relative 'openapi_ruby_sdk/models/create_call_request'
require_relative 'openapi_ruby_sdk/models/create_call_response'
require_relative 'openapi_ruby_sdk/models/deferred_result'
require_relative 'openapi_ruby_sdk/models/diversion'
require_relative 'openapi_ruby_sdk/models/error'
require_relative 'openapi_ruby_sdk/models/error_with_request'
require_relative 'openapi_ruby_sdk/models/forbidden_request'
require_relative 'openapi_ruby_sdk/models/inline_response200'
require_relative 'openapi_ruby_sdk/models/machine_detection_configuration'
require_relative 'openapi_ruby_sdk/models/media'
require_relative 'openapi_ruby_sdk/models/message_request'
require_relative 'openapi_ruby_sdk/models/messaging_exception'
require_relative 'openapi_ruby_sdk/models/modify_call_recording_request'
require_relative 'openapi_ruby_sdk/models/modify_call_request'
require_relative 'openapi_ruby_sdk/models/modify_conference_request'
require_relative 'openapi_ruby_sdk/models/page_info'
require_relative 'openapi_ruby_sdk/models/participant'
require_relative 'openapi_ruby_sdk/models/participant_subscription'
require_relative 'openapi_ruby_sdk/models/session'
require_relative 'openapi_ruby_sdk/models/subscriptions'
require_relative 'openapi_ruby_sdk/models/tag'
require_relative 'openapi_ruby_sdk/models/transcribe_recording_request'
require_relative 'openapi_ruby_sdk/models/transcript'
require_relative 'openapi_ruby_sdk/models/transcription'
require_relative 'openapi_ruby_sdk/models/transcription_metadata'
require_relative 'openapi_ruby_sdk/models/transcription_response'
require_relative 'openapi_ruby_sdk/models/two_factor_code_request_schema'
require_relative 'openapi_ruby_sdk/models/two_factor_messaging_response'
require_relative 'openapi_ruby_sdk/models/two_factor_verify_code_response'
require_relative 'openapi_ruby_sdk/models/two_factor_verify_request_schema'
require_relative 'openapi_ruby_sdk/models/two_factor_voice_response'
require_relative 'openapi_ruby_sdk/models/unauthorized_request'

# APIs
require_relative 'openapi_ruby_sdk/api/calls_api'
require_relative 'openapi_ruby_sdk/api/conferences_api'
require_relative 'openapi_ruby_sdk/api/mfa_api'
require_relative 'openapi_ruby_sdk/api/media_api'
require_relative 'openapi_ruby_sdk/api/messages_api'
require_relative 'openapi_ruby_sdk/api/participants_api'
require_relative 'openapi_ruby_sdk/api/recordings_api'
require_relative 'openapi_ruby_sdk/api/sessions_api'

module RubySdk
  class << self
    # Customize default settings for the SDK using block.
    #   RubySdk.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
